ALTER TYPE "LearningActivityType" ADD VALUE 'TEST_PART_PRACTICE';
ALTER TYPE "LearningActivityType" ADD VALUE 'TEST_MOCK';
ALTER TYPE "LearningActivityType" ADD VALUE 'DICTATION';
ALTER TYPE "LearningActivityType" ADD VALUE 'VOCABULARY_REVIEW';
