services:
  postgres:
    image: postgres:16-alpine
    container_name: engvocab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: engvocab
      POSTGRES_PASSWORD: engvocab
      POSTGRES_DB: engvocab
    ports:
      - '5433:5432'
    volumes:
      - engvocab_postgres_data:/var/lib/postgresql/data

volumes:
  engvocab_postgres_data:
